# Static configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false

entryPoints:
  web:
    address: ":3838"
    transport:
      respondingTimeouts:
        idleTimeout: 0
      lifeCycle:
        requestAcceptGraceTimeout: 900s
        graceTimeOut: 10s

providers:
  file:
    directory: /etc/traefik
    watch: true

log:
  level: INFO
  # filePath: /var/log/traefik/traefik.log

accessLog:
  # filePath: /var/log/traefik/access.log
