# Static configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: false

entryPoints:
  web:
    address: ":3838"
    transport:
      respondingTimeouts:
        readTimeout: 900s # 15 minutes
        writeTimeout: 900s # 15 minutes
        idleTimeout: 900s # 15 minutes
      lifeCycle:
        requestAcceptGraceTimeout: 900s
        graceTimeOut: 10s

providers:
  file:
    directory: /etc/traefik
    watch: true

log:
  level: INFO
  # filePath: /var/log/traefik/traefik.log

accessLog:
  # filePath: /var/log/traefik/access.log

serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: 10
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 900s # 15 minutes
    idleConnTimeout: 900s # 15 minutes
