name: "Publish Docker image to AWS ECR and deploy to ECS"

on:
  push:
    branches:
      - dev
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub-to-AWS
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set image tag from branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" == "master" ]]; then
            echo "TAGNAME=latest" >> $GITHUB_ENV
          else
            CLEAN_TAG=${BRANCH_NAME//\//_}
            echo "TAGNAME=$CLEAN_TAG" >> $GITHUB_ENV
          fi

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        run: |
          ECR_URI=$(aws ecr describe-repositories \
            --repository-names ${{ secrets.ECR_REPOSITORY }} \
            --region ${{ secrets.AWS_REGION }} \
            --query 'repositories[0].repositoryUri' \
            --output text)

          echo "Using ECR URI: $ECR_URI"
          echo "Using tag: $TAGNAME"
          docker build --no-cache -t ${{ secrets.ECR_REPOSITORY }}:$TAGNAME .
          docker tag ${{ secrets.ECR_REPOSITORY }}:$TAGNAME $ECR_URI:$TAGNAME
          docker push $ECR_URI:$TAGNAME

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}

      - name: Delete all untagged images from ECR
        run: |
          UNTAGGED_DIGESTS=$(aws ecr list-images \
            --repository-name ${{ secrets.ECR_REPOSITORY }} \
            --region ${{ secrets.AWS_REGION }} \
            --filter tagStatus=UNTAGGED \
            --query 'imageIds[*].imageDigest' \
            --output text)

          if [ -z "$UNTAGGED_DIGESTS" ]; then
            echo "No untagged images to delete."
          else
            for digest in $UNTAGGED_DIGESTS; do
              echo "Deleting untagged image with digest: $digest"
              aws ecr batch-delete-image \
                --repository-name ${{ secrets.ECR_REPOSITORY }} \
                --region ${{ secrets.AWS_REGION }} \
                --image-ids imageDigest=$digest
            done
          fi
